[workspace]

members = [ "blog", "collections_tasks", "concurrency", "first_tasks", "guessing_game", "minigrep", "smart_pointer", "web_server", "web_server_thread_pool_from_crates_io", ]
resolver = "2"
