[package]
name = "web_server_thread_pool_from_crates_io"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
threadpool = "1.8.1"
futures = { version = "0.3.30", features = ["thread-pool"] }
